In [1]:
#import library

import numpy as np
import pandas as pd
import matplotlib as mlt

## Exploring Customer File

In [2]:
# Explore 1st Customer Files
customer = pd.read_csv("customers.csv")
customer.head(10)

,Customer_ID,Customer_Name,Age,Gender,Country,STATE,Email,Phone_Number,Signup_Date
0,C1000,Charvi Sibal,forty two,NaN,India,delhi,nandini30@example.net,9.138190e+11,1/26/2025
1,C1001,Hritik Gala,twenty five,NaN,usa,karnataka,harshildhar@example.com,2.232729e+09,1/15/2024
2,C1002,Adya Sunder,forty two,M,USA,Maharashtra,kritikagade@example.org,5.490818e+09,12/6/2023
3,C1003,Ekiya Palan,twenty five,Fem,usa,tamilnadu,anyamuni@example.net,8.147270e+09,3/28/2022
4,C1004,Vedant Krishna,twenty five,F,USA,karnataka,harrisonshere@example.org,9.148070e+11,2/8/2024
5,C1005,Kashish Subramaniam,twenty five,F,Bharat,Delhi,chakradharsachdev@example.org,9.871558e+08,6/15/2021
6,C1006,Vasana Butala,forty two,female,uk,DL,geetikagopal@example.org,9.180010e+11,11/3/2023
7,C1007,Vivaan Brahmbhatt,twenty five,M,UK,delhi,advik92@example.org,6.441737e+09,5/1/2024
8,C1008,Adya Goswami,19,NaN,Bharat,Tamil Nadu,xluthra@example.org,6.151395e+09,4/16/2021
9,C1009,Manthan Batra,thirty,F,IND,tamilnadu,seshadrimanan@example.org,9.734318e+09,12/11/2025

In [3]:
#Number of Rows and Columns
customer.shape

(40000, 9)

In [4]:
customer.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40000 entries, 0 to 39999
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Customer_ID    40000 non-null  object
 1   Customer_Name  40000 non-null  object
 2   Age            40000 non-null  object
 3   Gender         33215 non-null  object
 4   Country        40000 non-null  object
 5   STATE          40000 non-null  object
 6   Email          40000 non-null  object
 7   Phone_Number   40000 non-null  float64
 8   Signup_Date    40000 non-null  object
dtypes: float64(1), object(8)
memory usage: 2.7+ MB

In [5]:
customer.describe()

       Phone_Number
count  4.000000e+04
mean   3.086080e+11
std    4.290802e+11
min    1.018000e+04
25%    3.781095e+09
50%    7.528603e+09
75%    9.125295e+11
max    9.200000e+11

In [6]:
#Null data
customer.isnull().sum()/len(customer)*100

Customer_ID       0.0000
Customer_Name     0.0000
Age               0.0000
Gender           16.9625
Country           0.0000
STATE             0.0000
Email             0.0000
Phone_Number      0.0000
Signup_Date       0.0000
dtype: float64

In [7]:
#Number of duplicates in list
customer[customer.duplicated()].shape

(0, 9)

In [8]:
#Repeated values in list
customer['Customer_ID'].value_counts()

Customer_ID
C40983    1
C40982    1
C40981    1
C40980    1
C40979    1
         ..
C1004     1
C1003     1
C1002     1
C1001     1
C1000     1
Name: count, Length: 40000, dtype: int64

In [9]:
#Checking all unique values in categorical columns
for col in customer.columns:
    if customer[col].nunique()<20:
        print(customer[col].value_counts())
        print('-'*40)

Gender
Fem       6666
M         6659
Male      6642
F         6638
female    6610
Name: count, dtype: int64
----------------------------------------
Country
uk           3419
UK           3404
uae          3386
USA          3362
australia    3362
India        3343
Australia    3325
Bharat       3319
india        3300
usa          3299
UAE          3276
IND          3205
Name: count, dtype: int64
----------------------------------------
STATE
maharastra     3427
karnataka      3385
TN             3374
DL             3367
tamilnadu      3355
KA             3346
Karnataka      3346
delhi          3320
Tamil Nadu     3320
MH             3275
Delhi          3262
Maharashtra    3223
Name: count, dtype: int64
----------------------------------------

In [10]:
customer['Age'].unique()

array(['forty two', 'twenty five', '19', 'thirty', '51', '24', '46', '29',
       '39', '54', '49', '60', '59', '22', '45', '52', '28', '23', '34',
       '37', '55', '47', '58', '33', '31', '30', '40', '44', '32', '57',
       '18', '26', '38', '42', '56', '20', '48', '27', '50', '21', '25',
       '43', '35', '53', '41', '36'], dtype=object)

### Erros In Customer Columns
* Data Type Of Age & Sign Up is incorrect 
* In Table 16.9% customers Gender is null
* Few Age details  are in words form
* Inconsitance format of Gender,Country and State Columns

# Exploring  Product Files

In [11]:
# importing product files

products = pd.read_csv('products.csv')
products.head(10)

  Product_ID Product_Name     Category        Price         Cost
0      P1000         rice      Grocery  3046.938364  2425.772522
1      P1001        phone      Fashion  4443.782786  2355.256606
2      P1002        shirt      Fashion  3265.268163   537.243408
3      P1003         Rice  Electronics   -50.000000  2420.537344
4      P1004       laptop      fashion   -50.000000  2211.984915
5      P1005         Rice  Electronics   -50.000000  2019.297723
6      P1006       Laptop  electronics  2957.592560   468.970976
7      P1007       laptop      fashion   -50.000000  1342.466238
8      P1008        Phone  Electronics   -50.000000  1121.642151
9      P1009        Shirt      Grocery  1164.732753  1482.151680

In [34]:
products.shape

(40000, 5)

In [35]:
products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40000 entries, 0 to 39999
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Product_ID    40000 non-null  object
 1   Product_Name  40000 non-null  object
 2   Category      40000 non-null  object
 3   Price         40000 non-null  float64
 4   Cost          40000 non-null  float64
dtypes: float64(2), object(3)
memory usage: 1.5+ MB

In [36]:
products.describe()

              Price          Cost
count  40000.000000  40000.000000
mean    1233.232993   1502.578149
std     1639.390960    863.229881
min      -50.000000      5.048728
25%      -50.000000    753.731379
50%       13.708411   1501.817015
75%     2520.297308   2249.430844
max     4999.683863   2999.992177

In [38]:
products[products.duplicated()].shape

(0, 5)

In [39]:
products['Product_ID'].value_counts()

Product_ID
P40983    1
P40982    1
P40981    1
P40980    1
P40979    1
         ..
P1004     1
P1003     1
P1002     1
P1001     1
P1000     1
Name: count, Length: 40000, dtype: int64

In [40]:
for col in products.columns:
    if products[col].nunique() <20:
        print(products[col].value_counts())
        print("-"*40)

Product_Name
Laptop    5104
Shirt     5054
laptop    5043
Rice      4991
rice      4977
Phone     4964
shirt     4955
phone     4912
Name: count, dtype: int64
----------------------------------------
Category
Electronics    6711
electronics    6706
Grocery        6673
grocery        6669
fashion        6663
Fashion        6578
Name: count, dtype: int64
----------------------------------------

## Errors in Product Data Sets
* Price of products shows invalid values (negative prices), skewed distribution also selling price is lower than cost.
* In consitance format of Product name & Category Columns

# Exploring  Orders Files

In [42]:
# Explorting Orders Files
Orders= pd.read_csv('Orders.csv')
Orders.head(10)

  Order_ID Customer_ID  Order_Date Order_Status Shipping Date
0    O1000      C12603  2020-04-22      Pending    2020-05-04
1    O1001       C3535  2024-08-25    Completed    2024-09-02
2    O1002      C11568  2021-08-27    Cancelled    2021-08-31
3    O1003       C8400  2024-07-13    Completed    2024-07-25
4    O1004      C23777  2020-02-10    Completed    2020-02-14
5    O1005      C11763  2022-10-19      Pending    2022-11-02
6    O1006      C12155  2025-07-31    Cancelled    2025-08-03
7    O1007       C7656  2025-09-13    Completed    2025-09-14
8    O1008       C1643  2023-06-12    Cancelled    2023-06-20
9    O1009      C20581  2023-03-16    Completed    2023-03-25

In [44]:
Orders.describe()

       Order_ID Customer_ID  Order_Date Order_Status Shipping Date
count     40000       40000       40000        40000         40000
unique    40000       25421        2192            4          2204
top      O40983      C37757  2022-05-07      Pending    2022-08-15
freq          1           9          33        10151            36

In [45]:
Orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40000 entries, 0 to 39999
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       40000 non-null  object
 1   Customer_ID    40000 non-null  object
 2   Order_Date     40000 non-null  object
 3   Order_Status   40000 non-null  object
 4   Shipping Date  40000 non-null  object
dtypes: object(5)
memory usage: 1.5+ MB

In [46]:
Orders.isnull().sum()

Order_ID         0
Customer_ID      0
Order_Date       0
Order_Status     0
Shipping Date    0
dtype: int64

In [49]:
Orders[Orders.duplicated()].shape

(0, 5)

In [51]:
Orders['Order_Date'].unique()

array(['2020-04-22', '2024-08-25', '2021-08-27', ..., '2020-03-18',
       '2023-03-26', '2022-07-29'], dtype=object)

In [53]:
Orders['Shipping Date'].unique()

array(['2020-05-04', '2024-09-02', '2021-08-31', ..., '2020-11-05',
       '2024-03-17', '2020-09-22'], dtype=object)

In [57]:
for col in Orders.columns:
    if Orders[col].nunique()<20:
        print(Orders[col].value_counts())
        print('-'*40)

Order_Status
Pending      10151
completed    10038
Completed    10000
Cancelled     9811
Name: count, dtype: int64
----------------------------------------

### Erros In Orders Data Set
* Incorrect Data Type of order_date & Shipping_date 
* Inconsitance format of Order_Status

# Exploring  Order_items Files

In [3]:
#Importing Order_items file
Order_items = pd.read_csv('order_items.csv')
Order_items.head(10)

  Order_Item_ID Order_ID Product_ID  Quantity  Price_per_Unit  Total_Amount
0           OI0   O29876     P24513         3       21.577537     54.732610
1           OI1   O35515      P9928         3      391.407859   1179.223576
2           OI2   O19039     P22714         1      317.881464    322.881464
3           OI3    O4528     P36746         3       51.274048    143.822145
4           OI4   O40524     P24559         4      197.118517    778.474066
5           OI5   O32648     P26140         4      185.709633    747.838530
6           OI6   O10129     P14537         3      322.443128    967.329385
7           OI7   O36529      P2789         3      249.940067    754.820200
8           OI8   O16410     P33731         4      142.377968    559.511873
9           OI9    O6006     P14876         5      142.534535    712.672674

In [7]:
#Checking Data types and non-nulls
Order_items.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40000 entries, 0 to 39999
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order_Item_ID   40000 non-null  object
 1   Order_ID        40000 non-null  object
 2   Product_ID      40000 non-null  object
 3   Quantity        40000 non-null  int64
 4   Price_per_Unit  40000 non-null  float64
 5   Total_Amount    40000 non-null  float64
dtypes: float64(2), int64(1), object(3)
memory usage: 1.8+ MB

In [8]:
#Numerical data insights
Order_items.describe()

           Quantity  Price_per_Unit  Total_Amount
count  40000.000000    40000.000000  40000.000000
mean       2.997800      254.505916    762.535671
std        1.418078      141.303903    593.538403
min        1.000000       10.001579      0.661175
25%        2.000000      131.984257    287.030829
50%        3.000000      255.128945    601.529799
75%        4.000000      376.535396   1127.494425
max        5.000000      499.997149   2504.330425

In [9]:
#Checking if there is null value
Order_items.isnull().sum()

Order_Item_ID     0
Order_ID          0
Product_ID        0
Quantity          0
Price_per_Unit    0
Total_Amount      0
dtype: int64

In [10]:
#Checking the duplicates
Order_items[Order_items.duplicated()].shape

(0, 6)

In [11]:
#Checking if there is multipler order_items id
Order_items['Order_Item_ID'].value_counts()

Order_Item_ID
OI39983    1
OI39982    1
OI39981    1
OI39980    1
OI39979    1
          ..
OI4        1
OI3        1
OI2        1
OI1        1
OI0        1
Name: count, Length: 40000, dtype: int64

In [12]:
# Checking that does the quantity * per unit price is equal to total amounts
Order_items[Order_items['Quantity']*Order_items['Price_per_Unit']!= Order_items['Total_Amount']]

,Order_Item_ID,Order_ID,Product_ID,Quantity,Price_per_Unit,Total_Amount
0,OI0,O29876,P24513,3,21.577537,54.732610
1,OI1,O35515,P9928,3,391.407859,1179.223576
2,OI2,O19039,P22714,1,317.881464,322.881464
3,OI3,O4528,P36746,3,51.274048,143.822145
4,OI4,O40524,P24559,4,197.118517,778.474066
...,...,...,...,...,...,...
39994,OI39994,O28016,P7505,4,266.390964,1070.563855
39995,OI39995,O29009,P13060,2,120.558769,246.117537
39996,OI39996,O33243,P17453,3,85.568144,246.704431
39998,OI39998,O10390,P26439,2,105.825918,216.651836
39999,OI39999,O33535,P3632,3,140.518392,426.555177

### Erros In Order Items Data Set
* The Calculation of Quantity * Per Unit Price is not equal to Total Amount

# Exploring Payments Files

In [13]:
#Importing Payments File 
Payments = pd.read_csv('payments.csv')
Payments.head(10)

  Payment_ID Order_ID Payment_Date Payment_Method Payment_Status  Amount_Paid
0        PM0   O26974   2022-02-19           Card         Failed  1731.257172
1        PM1    O7829   2020-07-18           card           Paid  2629.996344
2        PM2   O21870   2020-02-04            COD           Paid  4275.022628
3        PM3    O9235   2023-07-29            COD           Paid  3785.645385
4        PM4   O19776   2020-07-21            upi           paid  3146.535505
5        PM5   O30454   2022-04-05           Card           paid  4356.096476
6        PM6   O22638   2025-09-29            COD         Failed  2749.663434
7        PM7    O2454   2023-06-27            UPI         Failed  4343.129267
8        PM8    O3383   2020-04-01            UPI           paid  4647.942138
9        PM9   O24775   2023-09-30            upi           Paid  2357.665830

In [18]:
#Table Info
Payments.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40000 entries, 0 to 39999
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Payment_ID      40000 non-null  object
 1   Order_ID        40000 non-null  object
 2   Payment_Date    40000 non-null  object
 3   Payment_Method  40000 non-null  object
 4   Payment_Status  40000 non-null  object
 5   Amount_Paid     40000 non-null  float64
dtypes: float64(1), object(5)
memory usage: 1.8+ MB

In [17]:
#Checking Duplicate values
Payments[Payments.duplicated()].shape

(0, 6)

In [16]:
for col in Payments.columns:
    if Payments[col].nunique()<20:
        print(Payments[col].value_counts())
        print('-'*40)

Payment_Method
upi     8054
UPI     8016
COD     7997
Card    7973
card    7960
Name: count, dtype: int64
----------------------------------------
Payment_Status
paid      13415
Failed    13391
Paid      13194
Name: count, dtype: int64
----------------------------------------

### Erros In Payment Data Set
* Incorrect Data Type of Payment_Date
* Inconsitance format of Payment_Method & Payment_Status

# Exploring Returns File

In [19]:
#Importing Returns File 
Returns = pd.read_csv('returns.csv')
Returns.head(10)

  Return_ID Order_ID Product_ID Return_Date Return_Reason  Refund_Amount
0        R0    O1699     P13184  2025-06-27       damaged     140.582052
1        R1   O10577     P37295  2020-03-15    Wrong Item     278.028860
2        R2   O34663     P25920  2020-12-25       Damaged     292.496508
3        R3   O39857     P11870  2021-09-27          Late     492.094245
4        R4    O7232     P40318  2023-10-20    Wrong Item     416.244628
5        R5   O36395     P27036  2022-09-10    Wrong Item     179.858417
6        R6   O27523     P16001  2024-09-08       damaged     373.105883
7        R7   O28520     P29736  2022-09-14          Late     420.119045
8        R8   O12696     P29304  2024-07-29       Damaged     102.537946
9        R9   O22511     P10233  2021-11-19       damaged     305.917040

In [21]:
Returns.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40000 entries, 0 to 39999
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Return_ID      40000 non-null  object
 1   Order_ID       40000 non-null  object
 2   Product_ID     40000 non-null  object
 3   Return_Date    40000 non-null  object
 4   Return_Reason  40000 non-null  object
 5   Refund_Amount  40000 non-null  float64
dtypes: float64(1), object(5)
memory usage: 1.8+ MB

In [22]:
Returns[Returns.duplicated()].shape

(0, 6)

In [23]:
Returns['Return_ID'].value_counts()

Return_ID
R39983    1
R39982    1
R39981    1
R39980    1
R39979    1
         ..
R4        1
R3        1
R2        1
R1        1
R0        1
Name: count, Length: 40000, dtype: int64

In [24]:
for col in Returns.columns:
    if Returns[col].nunique()<20:
        print(Returns[col].value_counts())
        print('-'*40)

Return_Reason
Damaged       10191
damaged        9989
Late           9961
Wrong Item     9859
Name: count, dtype: int64
----------------------------------------

### Erros In Returns Set
* Incorrect Data Type of Return_Date 
* Inconsitance format of Return_Reason

# Exploring Reviews File

In [26]:
#Importing Returns File 
Reviews = pd.read_csv('reviews.csv')
Reviews.head(10)

  Review_id Customer_id Product_id  Rating Review text review date
0       RV0      C26263     P31065       5     Average  2024-09-24
1       RV1      C15009     P36269       5        poor  2021-01-21
2       RV2      C12865     P25031       3        Good  2023-02-20
3       RV3       C9560     P29466       3         bad  2023-01-19
4       RV4      C37926     P22717       4     Average  2025-03-17
5       RV5      C14029     P34178       2         bad  2023-07-02
6       RV6      C11818      P4536       5     Average  2020-11-07
7       RV7      C10365      P1406       3        Good  2025-06-20
8       RV8      C25722     P22302       1   excellent  2021-10-31
9       RV9      C32739     P17123       1        Good  2020-01-13

In [27]:
Reviews.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40000 entries, 0 to 39999
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Review_id    40000 non-null  object
 1   Customer_id  40000 non-null  object
 2   Product_id   40000 non-null  object
 3   Rating       40000 non-null  int64
 4   Review text  40000 non-null  object
 5   review date  40000 non-null  object
dtypes: int64(1), object(5)
memory usage: 1.8+ MB

In [28]:
Reviews.describe()

             Rating
count  40000.000000
mean       3.006050
std        1.413776
min        1.000000
25%        2.000000
50%        3.000000
75%        4.000000
max        5.000000

In [29]:
Reviews[Reviews.duplicated()].shape

(0, 6)

In [30]:
for col in Reviews.columns:
    if Reviews[col].nunique()<20:
        print(Reviews[col].value_counts())
        print('-'*40)

Rating
2    8076
5    8051
4    8034
3    7930
1    7909
Name: count, dtype: int64
----------------------------------------
Review text
bad          8177
Good         7997
poor         7971
excellent    7966
Average      7889
Name: count, dtype: int64
----------------------------------------

### Erros In Reviews Set
* Incorrect Data Type of review date
* Incorrect format of review date column name
* Inconsitance format of Review text